import type { Tech } from "@/types";

export const techStack: Tech[] = [
  {
    name: "React",
    icon: "/assets/images/techlogo/react.svg",
    color: "#61DAFB",
    experience: 0.9,
  },
  {
    name: "Next.js",
    icon: "/assets/images/techlogo/nextjs-transparent.svg",
    color: "#bdbdbd",
    experience: 0.9,
  },
  {
    name: "Typescript",
    icon: "/assets/images/techlogo/ts.svg",
    color: "#007acc",
    experience: 0.9,
  },
  {
    name: "Tailwind CSS",
    icon: "/assets/images/techlogo/tailwind.svg",
    color: "#38b2ac",
    experience: 0.8,
  },
  {
    name: "Turborepo",
    icon: "/assets/images/techlogo/turborepo.svg",
    color: "#bf0477",
    experience: 0.7,
  },
  {
    name: "Supabase",
    icon: "/assets/images/techlogo/supabase.svg",
    color: "#18b870",
    experience: 0.8,
  },
  {
    name: "MySQL",
    icon: "/assets/images/techlogo/mysql.svg",
    color: "#00618A",
    experience: 0.7,
  },
  {
    name: "Firebase",
    icon: "/assets/images/techlogo/firebase.svg",
    color: "#f58220",
    experience: 0.9,
  },
  {
    name: "NodeJS",
    icon: "/assets/images/techlogo/nodejs.svg",
    color: "#83CD29",
    experience: 0.9,
  },
  {
    name: "Redux",
    icon: "/assets/images/techlogo/redux.svg",
    color: "#764abc",
    experience: 0.8,
  },
  {
    name: "Flutter",
    icon: "/assets/images/techlogo/flutter.svg",
    color: "#27AACD",
    experience: 0.7,
  },
  {
    name: "Go",
    icon: "/assets/images/techlogo/go.svg",
    color: "#00acd7",
    experience: 0.8,
  },
  {
    name: "Docker",
    icon: "/assets/images/techlogo/docker.svg",
    color: "#0db7ed",
    experience: 0.8,
  },
  {
    name: "Python",
    icon: "/assets/images/techlogo/python.svg",
    color: "#306998",
    experience: 0.9,
  },
  {
    name: "FastAPI",
    icon: "/assets/images/techlogo/fastapi.svg",
    color: "#306998",
    experience: 0.8,
  },
  {
    name: "OpenCV",
    icon: "/assets/images/techlogo/opencv.svg",
    color: "#306998",
    experience: 0.9,
  },
  {
    name: "Mediapipe",
    icon: "/assets/images/techlogo/mediapipe.png",
    color: "#306998",
    experience: 0.8,
  },
  {
    name: "PyQT5",
    icon: "/assets/images/techlogo/pyqt5.svg",
    color: "#306998",
    experience: 0.9,
  },
  {
    name: "Pytorch",
    icon: "/assets/images/techlogo/pytorch.svg",
    color: "#306998",
    experience: 0.5,
  },
  {
    name: "C",
    icon: "/assets/images/techlogo/c.svg",
    color: "#306998",
    experience: 0.8,
  },
  {
    name: "Redis",
    icon: "/assets/images/techlogo/redis.svg",
    color: "#306998",
    experience: 0.7,
  },
  {
    name: "Selenium",
    icon: "/assets/images/techlogo/selenium.svg",
    color: "#306998",
    experience: 0.7,
  },
  {
    name: "Playwright",
    icon: "/assets/images/techlogo/playwright.svg",
    color: "#306998",
    experience: 0.6,
  },
  {
    name: "Electron js",
    icon: "/assets/images/techlogo/electron.svg",
    color: "#306998",
    experience: 0.9,
  },
  {
    name: "Tauri",
    icon: "/assets/images/techlogo/tauri.svg",
    color: "#306998",
    experience: 0.6,
  },
];
